name: "Wheel Tracker"
description: "Options trading wheel strategy tracker"
version: "1.0.0"
slug: "wheel_tracker"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
ingress: true
panel_icon: mdi:chart-line
panel_title: Wheel Tracker
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: Web interface (not required for ingress)
options:
  database_path: "/config/wheel-tracker/database.db"
  log_level: "info"
schema:
  database_path: "str"
  log_level: "list(trace|debug|info|notice|warning|error|fatal)" 